name: Backend CI

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
        #step 1 Download the repository gcode onto the runner
        - name: checkout repository code 
          uses: actions/checkout@v4

        #step 2 set up the node.js environment with given version
        - name: Set up node.js
          uses: actions/setup-node@v4
          with:
              node-version: 22

        #step 4 install the dependency 
        - name: Install dependency
          run: npm ci

        # #step 4 lint check typescript 
        # - name: lint check 
        #   run: npm run lint:check

        #step 5 test 
        - name: run automated tests
          run: npm test

        #step 6 build
        - name: build code
          run: npm run build

        #step 7 upload artifact
        - name: upload build artifact
          uses: actions/upload-artifact@v4
          with:
            name: nestjs-build
            path: dist/

  download-artifact: 
    needs: build-and-test
    runs-on: ubuntu latest

    steps:
        - name: download build artifact
          uses: actions/upload-artifact@v4
          with: 
            name: nestjs-build

        - name: inspect artifact
          run: find . -maxdepth 3 -type f       


       


      

